### ISSUE TITLE
Chrome 名称拼写有误

### ISSUE THREAD

**Issue by beta** [xiangsudian/CaoMei#1]
Chrome 的图标名称拼写成了“chorme”，分别位于 selection.json 的[第 1567 行](https://github.com/xiangsudian/CaoMei/blob/master/selection.json#L1567) 和[第 1576 行](https://github.com/xiangsudian/CaoMei/blob/master/selection.json#L1576)。网站中的“czs-chorme”也需要修改。

**Comment by xiangsudian** [comment]
感谢，已收到！会在一个小版本更新解决掉

**Comment by xiangsudian** [comment]
已经更新了1.0.1，问题已修复！
