### ISSUE TITLE
[help] 开源项目希望得到 pro 版本使用权限

### ISSUE THREAD

**Issue by WittBulter** [xiangsudian/CaoMei#23]
非常酷的图标库！
我有一个开源项目 (MIT 协议) 希望能够得到 `CaoMei` 的 pro 版本使用权限，可以联系我的邮箱。非常感谢您的项目。

1. [项目地址](https://github.com/zeit-ui/vue)
2. 邮箱: `lambdas.dev@gmail.com`

**Comment by xiangsudian** [comment]
Pro版本已经发你邮箱了，不知道Gmail是否会拦截一些图标CSS程序文件，如过没有收到请给一个国内邮箱。

**Comment by WittBulter** [comment]
等了一段时间发现果然是被拦截了，`nanazuimeng123@163.com` 麻烦你重新发送一下。(如果有时间)
非常感谢。Issue 先关掉了。
