### ISSUE TITLE
message图标是否略宽了一点？

### ISSUE THREAD

**Issue by cyyyu** [xiangsudian/CaoMei#3]
首先，很喜欢你的这套图标。

提个小意见，message图标是否略宽了一点？参考截图，以下几个我设置了同样的字号。

<img width="58" alt="screen shot 2017-06-16 at 12 29 31 am" src="https://user-images.githubusercontent.com/15100664/27191628-fd6c32f8-522a-11e7-9fa6-4d166f3cbca4.png">

**Comment by xiangsudian** [comment]
感谢你的建议，后续我们会再次优化下，不管是质量上还是 数量上。谢谢支持！

**Comment by xiangsudian** [comment]
已经更新了1.0.1，问题已修复！

**Comment by cyyyu** [comment]
@xiangsudian 感谢。
